# Generated by Django 4.2.1 on 2023-05-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_attendancerange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceclass',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2023-1-20'),
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DOB',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
