# Generated by Django 4.2.1 on 2023-05-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_attendanceclass_options_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='sem',
        ),
    ]
